#ifndef CHESS_CORNERS_FFI_H
#define CHESS_CORNERS_FFI_H

#pragma once

/* Auto-generated by `cargo run -p chess-corners-capi --bin generate-ffi-header --features generate-header`. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Status returned by fallible entry points.
 *
 * This is the only Rust enum in the ABI: it is produced by the library and
 * read by C, so an invalid discriminant can never be loaded from C-filled
 * memory.
 */
typedef enum cc_status {
  /**
   * Success.
   */
  CC_OK = 0,
  /**
   * A required pointer argument was null.
   */
  CC_ERR_NULL_POINTER,
  /**
   * The image dimensions were invalid (zero, or `width * height`
   * overflows `size_t`).
   */
  CC_ERR_DIMENSION_MISMATCH,
  /**
   * The upscale configuration was invalid.
   */
  CC_ERR_UPSCALE,
  /**
   * The configuration was invalid (e.g. an enum tag was out of range, or
   * a refiner not valid for the selected strategy).
   */
  CC_ERR_INVALID_CONFIG,
  /**
   * A panic was trapped at the FFI boundary.
   */
  CC_ERR_PANIC,
} cc_status;

/**
 * Detector strategy tag stored in `cc_config::strategy`.
 */
typedef uint32_t cc_strategy_t;

/**
 * Subpixel-refiner tag stored in `cc_config::refiner`.
 *
 * Refiner-specific tuning is not exposed over the flat ABI; the selected
 * refiner runs with its library defaults.
 */
typedef uint32_t cc_refiner_t;

/**
 * Orientation-fit tag stored in `cc_config::orientation_method`.
 */
typedef uint32_t cc_orientation_method_t;

/**
 * Flat, C-fillable detector configuration.
 *
 * Construct one with a preset (`cc_config_default`, `cc_config_chess`, …)
 * and tweak the exposed fields. Knobs not represented here (per-strategy
 * ring/ray geometry, refiner tuning, pre-detection upscaling, cross-level
 * merge radius) fall back to the selected strategy preset's defaults.
 */
typedef struct cc_config {
  /**
   * One of the `CC_STRATEGY_*` constants.
   */
  cc_strategy_t strategy;
  /**
   * Acceptance threshold. ChESS reads it as an absolute response floor;
   * Radon as a fraction of the per-frame maximum.
   */
  float threshold;
  /**
   * Non-maximum-suppression half-radius in working-resolution pixels.
   */
  uint32_t nms_radius;
  /**
   * Minimum positive-response neighbours required to accept a candidate.
   */
  uint32_t min_cluster_size;
  /**
   * One of the `CC_REFINER_*` constants. Must be valid for `strategy`.
   */
  cc_refiner_t refiner;
  /**
   * One of the `CC_ORIENTATION_*` constants.
   */
  cc_orientation_method_t orientation_method;
  /**
   * `0` runs single-scale detection; any non-zero value enables the
   * default three-level coarse-to-fine pyramid.
   */
  uint32_t multiscale;
} cc_config;

/**
 * One local grid-axis direction with its 1σ angular uncertainty.
 */
typedef struct cc_axis {
  /**
   * Axis direction in radians.
   */
  float angle;
  /**
   * 1σ angular uncertainty in radians.
   */
  float sigma;
} cc_axis;

/**
 * One detected chessboard corner in full-resolution image pixels.
 *
 * The two axes follow the joint polarity convention of the Rust
 * `CornerDescriptor`: `axes[0].angle` lies in `[0, π)` and `axes[1].angle`
 * in `(axes[0].angle, axes[0].angle + π)`, with the CCW arc between them
 * covering a dark sector of the corner.
 */
typedef struct cc_corner {
  /**
   * Subpixel x position.
   */
  float x;
  /**
   * Subpixel y position.
   */
  float y;
  /**
   * Raw, unnormalized detector response at the peak.
   */
  float response;
  /**
   * The two local grid-axis directions.
   */
  struct cc_axis axes[2];
} cc_corner;

/**
 * Owned array of detected corners returned by `cc_detect_u8`.
 *
 * The library allocates `corners`; release it with `cc_result_free`.
 */
typedef struct cc_result {
  /**
   * Pointer to `len` corners. May be null when `len == 0`.
   */
  struct cc_corner *corners;
  /**
   * Number of corners pointed to by `corners`.
   */
  size_t len;
} cc_result;

/**
 * ChESS kernel detector.
 */
#define CC_STRATEGY_CHESS 0

/**
 * Whole-image Radon detector.
 */
#define CC_STRATEGY_RADON 1

/**
 * Center-of-mass refiner. Valid for both strategies.
 */
#define CC_REFINER_CENTER_OF_MASS 0

/**
 * Förstner refiner. Valid for the ChESS strategy only.
 */
#define CC_REFINER_FORSTNER 1

/**
 * Saddle-point refiner. Valid for the ChESS strategy only.
 */
#define CC_REFINER_SADDLE_POINT 2

/**
 * Radon-peak refiner. Valid for the Radon strategy only.
 */
#define CC_REFINER_RADON_PEAK 3

/**
 * 16-sample ring Gauss-Newton fit (the default).
 */
#define CC_ORIENTATION_RING_FIT 0

/**
 * Full-disk crossing-line estimator with a ring-fit fallback.
 */
#define CC_ORIENTATION_DISK_FIT 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Default configuration (single-scale ChESS).
 */
struct cc_config cc_config_default(void);

/**
 * Single-scale ChESS preset.
 */
struct cc_config cc_config_chess(void);

/**
 * Three-level coarse-to-fine ChESS preset.
 */
struct cc_config cc_config_chess_multiscale(void);

/**
 * Single-scale Radon preset.
 */
struct cc_config cc_config_radon(void);

/**
 * Three-level coarse-to-fine Radon preset.
 */
struct cc_config cc_config_radon_multiscale(void);

/**
 * Detect corners in an 8-bit, row-major grayscale image.
 *
 * On `CC_OK`, `*out` owns a heap-allocated corner array that the caller
 * must release with `cc_result_free`. On any error status `*out` is left
 * untouched.
 *
 * # Safety
 *
 * - `pixels` must point to at least `width * height` readable bytes.
 * - `cfg` must point to a readable `cc_config`.
 * - `out` must point to a writable `cc_result`.
 */
enum cc_status cc_detect_u8(const uint8_t *pixels,
                            uint32_t width,
                            uint32_t height,
                            const struct cc_config *cfg,
                            struct cc_result *out);

/**
 * Release a `cc_result` previously written by `cc_detect_u8`.
 *
 * Null-safe and idempotent: after the call `r->corners` is null and
 * `r->len` is zero.
 *
 * # Safety
 *
 * `r` must be null, or point to a `cc_result` previously written by
 * `cc_detect_u8` and not yet freed.
 */
void cc_result_free(struct cc_result *r);

/**
 * Human-readable, static description of a status code.
 *
 * The returned pointer is a static, NUL-terminated string and must not be
 * freed. `status` must be a value previously returned by this library.
 */
const char *cc_status_str(enum cc_status status);

/**
 * ABI version of this library. Bumped manually on any breaking ABI change.
 */
uint32_t cc_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CHESS_CORNERS_FFI_H */
