#ifndef CHESS_CORNERS_FFI_H
#define CHESS_CORNERS_FFI_H

#pragma once

/* Auto-generated by `cargo run -p chess-corners-capi --bin generate-ffi-header --features generate-header`. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Status returned by fallible entry points.
 *
 * This is the only Rust enum in the ABI: it is produced by the library and
 * read by C, so an invalid discriminant can never be loaded from C-filled
 * memory.
 */
typedef enum cc_status {
  /**
   * Success.
   */
  CC_OK = 0,
  /**
   * A required pointer argument was null.
   */
  CC_ERR_NULL_POINTER,
  /**
   * The image dimensions were invalid (zero, or `width * height`
   * overflows `size_t`).
   */
  CC_ERR_DIMENSION_MISMATCH,
  /**
   * The upscale configuration was invalid.
   */
  CC_ERR_UPSCALE,
  /**
   * The configuration was invalid (e.g. an enum tag was out of range, or
   * a refiner not valid for the selected strategy).
   */
  CC_ERR_INVALID_CONFIG,
  /**
   * A panic was trapped at the FFI boundary.
   */
  CC_ERR_PANIC,
} cc_status;

/**
 * Detector strategy tag stored in `cc_config::strategy`.
 */
typedef uint32_t cc_strategy_t;

/**
 * Subpixel-refiner tag stored in `cc_config::refiner`.
 *
 * Refiner-specific tuning is not exposed over the flat ABI; the selected
 * refiner runs with its library defaults.
 */
typedef uint32_t cc_refiner_t;

/**
 * Orientation-fit tag stored in `cc_config::orientation_method`.
 */
typedef uint32_t cc_orientation_method_t;

/**
 * ChESS sampling-ring tag stored in `cc_config::chess_ring`.
 *
 * Applies to the ChESS strategy only; ignored when `strategy` is
 * `CC_STRATEGY_RADON`.
 */
typedef uint32_t cc_chess_ring_t;

/**
 * Radon subpixel peak-fit tag stored in `cc_config::peak_fit`.
 *
 * Applies to the Radon strategy only; ignored when `strategy` is
 * `CC_STRATEGY_CHESS`.
 */
typedef uint32_t cc_peak_fit_t;

/**
 * Flat, C-fillable detector configuration.
 *
 * Construct one with a preset (`cc_config_default`, `cc_config_chess`, …)
 * and tweak the exposed fields. Every `DetectorConfig` knob is
 * representable here except two that fall back to library defaults:
 * refiner-specific tuning (only the refiner *kind* is exposed) and the
 * multiscale pyramid detail (level count, minimum size, refinement
 * radius) behind the on/off `multiscale` switch.
 *
 * Fields are grouped by applicability: `chess_ring` applies to the
 * ChESS strategy only, while `ray_radius` / `image_upsample` /
 * `response_blur_radius` / `peak_fit` apply to the Radon strategy only.
 * Fields that do not apply to the active `strategy` are ignored.
 */
typedef struct cc_config {
  /**
   * One of the `CC_STRATEGY_*` constants.
   */
  cc_strategy_t strategy;
  /**
   * Acceptance threshold. ChESS reads it as an absolute response floor;
   * Radon as a fraction of the per-frame maximum.
   */
  float threshold;
  /**
   * Non-maximum-suppression half-radius in working-resolution pixels.
   */
  uint32_t nms_radius;
  /**
   * Minimum positive-response neighbours required to accept a candidate.
   */
  uint32_t min_cluster_size;
  /**
   * One of the `CC_REFINER_*` constants. Must be valid for `strategy`.
   */
  cc_refiner_t refiner;
  /**
   * One of the `CC_ORIENTATION_*` constants.
   */
  cc_orientation_method_t orientation_method;
  /**
   * `0` runs single-scale detection; any non-zero value enables the
   * default three-level coarse-to-fine pyramid.
   */
  uint32_t multiscale;
  /**
   * Cross-level duplicate-suppression radius in base-image pixels.
   * After coarse-level seeds are refined into the base image, refined
   * positions within this radius are merged into one output corner.
   */
  float merge_radius;
  /**
   * Pre-pipeline integer upscale factor. `0` disables upscaling (the
   * explicit off-state); `2`, `3`, or `4` upscale by that factor before
   * detection. Any other value (including `1`) is rejected with
   * `CC_ERR_UPSCALE`. Output coordinates are rescaled back to the input
   * pixel frame.
   */
  uint32_t upscale_factor;
  /**
   * One of the `CC_CHESS_RING_*` constants. Applies to the ChESS
   * strategy only; ignored for Radon.
   */
  cc_chess_ring_t chess_ring;
  /**
   * Radon ray half-length in working-resolution pixels (ray has
   * `2·ray_radius + 1` samples). Applies to the Radon strategy only;
   * ignored for ChESS. Clamped to at least `1` by the core detector.
   */
  uint32_t ray_radius;
  /**
   * Radon image-level supersampling factor applied before ray
   * integration (`1` or `2`). Applies to the Radon strategy only;
   * ignored for ChESS. Values `≥ 3` are clamped to `2`.
   */
  uint32_t image_upsample;
  /**
   * Half-size of the box blur applied to the Radon response map (`0`
   * disables it). Applies to the Radon strategy only; ignored for ChESS.
   */
  uint32_t response_blur_radius;
  /**
   * One of the `CC_PEAK_FIT_*` constants. Applies to the Radon strategy
   * only; ignored for ChESS.
   */
  cc_peak_fit_t peak_fit;
} cc_config;

/**
 * One local grid-axis direction with its 1σ angular uncertainty.
 */
typedef struct cc_axis {
  /**
   * Axis direction in radians.
   */
  float angle;
  /**
   * 1σ angular uncertainty in radians.
   */
  float sigma;
} cc_axis;

/**
 * One detected chessboard corner in full-resolution image pixels.
 *
 * The two axes follow the joint polarity convention of the Rust
 * `CornerDescriptor`: `axes[0].angle` lies in `[0, π)` and `axes[1].angle`
 * in `(axes[0].angle, axes[0].angle + π)`, with the CCW arc between them
 * covering a dark sector of the corner.
 */
typedef struct cc_corner {
  /**
   * Subpixel x position.
   */
  float x;
  /**
   * Subpixel y position.
   */
  float y;
  /**
   * Raw, unnormalized detector response at the peak.
   */
  float response;
  /**
   * The two local grid-axis directions. Valid only when
   * `has_orientation` is `1`; zeroed otherwise.
   */
  struct cc_axis axes[2];
  /**
   * `1` when `axes` holds a fitted orientation, `0` when the
   * orientation fit was skipped (`CC_ORIENTATION_NONE`) and `axes`
   * is zeroed.
   */
  uint8_t has_orientation;
} cc_corner;

/**
 * Owned array of detected corners returned by `cc_detect_u8`.
 *
 * The library allocates `corners`; release it with `cc_result_free`.
 */
typedef struct cc_result {
  /**
   * Pointer to `len` corners. May be null when `len == 0`.
   */
  struct cc_corner *corners;
  /**
   * Number of corners pointed to by `corners`.
   */
  size_t len;
} cc_result;

/**
 * ChESS kernel detector.
 */
#define CC_STRATEGY_CHESS 0

/**
 * Whole-image Radon detector.
 */
#define CC_STRATEGY_RADON 1

/**
 * Center-of-mass refiner. Valid for both strategies.
 */
#define CC_REFINER_CENTER_OF_MASS 0

/**
 * Förstner refiner. Valid for the ChESS strategy only.
 */
#define CC_REFINER_FORSTNER 1

/**
 * Saddle-point refiner. Valid for the ChESS strategy only.
 */
#define CC_REFINER_SADDLE_POINT 2

/**
 * 16-sample ring Gauss-Newton fit (the default).
 */
#define CC_ORIENTATION_RING_FIT 0

/**
 * Full-disk crossing-line estimator with a ring-fit fallback.
 */
#define CC_ORIENTATION_DISK_FIT 1

/**
 * Skip the per-corner orientation fit. Detected corners then have
 * `cc_corner::has_orientation == 0` and a zeroed `axes` array.
 */
#define CC_ORIENTATION_NONE 2

/**
 * Paper-default radius-5 ring (16 samples).
 */
#define CC_CHESS_RING_CANONICAL 0

/**
 * Radius-10 ring: a larger support window that samples farther from
 * the candidate centre.
 */
#define CC_CHESS_RING_BROAD 1

/**
 * Parabolic fit on the raw response values.
 */
#define CC_PEAK_FIT_PARABOLIC 0

/**
 * Parabolic fit on `log(response)` (Gaussian peak). The Radon default.
 */
#define CC_PEAK_FIT_GAUSSIAN 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Default configuration (single-scale ChESS).
 */
struct cc_config cc_config_default(void);

/**
 * Single-scale ChESS preset.
 */
struct cc_config cc_config_chess(void);

/**
 * Three-level coarse-to-fine ChESS preset.
 */
struct cc_config cc_config_chess_multiscale(void);

/**
 * Single-scale Radon preset.
 */
struct cc_config cc_config_radon(void);

/**
 * Three-level coarse-to-fine Radon preset.
 */
struct cc_config cc_config_radon_multiscale(void);

/**
 * Detect corners in an 8-bit, row-major grayscale image.
 *
 * On `CC_OK`, `*out` owns a heap-allocated corner array that the caller
 * must release with `cc_result_free`. On any error status `*out` is left
 * untouched.
 *
 * # Safety
 *
 * - `pixels` must point to at least `width * height` readable bytes.
 * - `cfg` must point to a readable `cc_config`.
 * - `out` must point to a writable `cc_result`.
 */
enum cc_status cc_detect_u8(const uint8_t *pixels,
                            uint32_t width,
                            uint32_t height,
                            const struct cc_config *cfg,
                            struct cc_result *out);

/**
 * Release a `cc_result` previously written by `cc_detect_u8`.
 *
 * Null-safe and idempotent: after the call `r->corners` is null and
 * `r->len` is zero.
 *
 * # Safety
 *
 * `r` must be null, or point to a `cc_result` previously written by
 * `cc_detect_u8` and not yet freed.
 */
void cc_result_free(struct cc_result *r);

/**
 * Human-readable, static description of a status code.
 *
 * The returned pointer is a static, NUL-terminated string and must not be
 * freed. `status` must be a value previously returned by this library.
 */
const char *cc_status_str(enum cc_status status);

/**
 * ABI version of this library. Bumped manually on any breaking ABI change.
 */
uint32_t cc_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CHESS_CORNERS_FFI_H */
