"""Type stubs for the chess_corners public surface.

These stubs mirror the runtime classes exposed by the compiled
``_native`` extension. Every public surface class lists its
attributes, classmethod factories, and serialization helpers so IDEs
and type checkers can offer accurate autocompletion.
"""

from __future__ import annotations

from enum import Enum
from os import PathLike
from typing import Any, Optional, TextIO, Union

import numpy as np

class ConfigError(ValueError): ...

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ChessRing(Enum):
    CANONICAL = ...
    BROAD = ...

class PeakFitMode(Enum):
    PARABOLIC = ...
    GAUSSIAN = ...

class OrientationMethod(Enum):
    RING_FIT = ...
    DISK_FIT = ...

# ---------------------------------------------------------------------------
# Leaf tuning configs
# ---------------------------------------------------------------------------

class CenterOfMassConfig:
    radius: int
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CenterOfMassConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "CenterOfMassConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

class ForstnerConfig:
    radius: int
    min_trace: float
    min_det: float
    max_condition_number: float
    max_offset: float
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ForstnerConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "ForstnerConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

class SaddlePointConfig:
    radius: int
    det_margin: float
    max_offset: float
    min_abs_det: float
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SaddlePointConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "SaddlePointConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

class RadonPeakConfig:
    ray_radius: int
    patch_radius: int
    image_upsample: int
    response_blur_radius: int
    peak_fit: PeakFitMode
    min_response: float
    max_offset: float
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RadonPeakConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "RadonPeakConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# DetectionParams (shared NMS / clustering knobs)
# ---------------------------------------------------------------------------

class DetectionParams:
    nms_radius: int
    min_cluster_size: int
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DetectionParams": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "DetectionParams": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# MultiscaleConfig (tagged class)
# ---------------------------------------------------------------------------

class MultiscaleConfig:
    kind: str
    # Pyramid-only fields raise AttributeError on the single_scale variant.
    levels: int
    min_size: int
    refinement_radius: int
    def __init__(self) -> None: ...
    @classmethod
    def single_scale(cls) -> "MultiscaleConfig": ...
    @classmethod
    def pyramid(
        cls, *, levels: int = ..., min_size: int = ..., refinement_radius: int = ...
    ) -> "MultiscaleConfig": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MultiscaleConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "MultiscaleConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# UpscaleConfig (tagged class)
# ---------------------------------------------------------------------------

class UpscaleConfig:
    kind: str
    # `factor` raises AttributeError on the disabled variant.
    factor: int
    def __init__(self) -> None: ...
    @classmethod
    def disabled(cls) -> "UpscaleConfig": ...
    @classmethod
    def fixed(cls, factor: int) -> "UpscaleConfig": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpscaleConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "UpscaleConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# Per-detector refiners (tagged classes)
# ---------------------------------------------------------------------------

class ChessRefiner:
    kind: str
    payload: Optional[
        Union[CenterOfMassConfig, ForstnerConfig, SaddlePointConfig]
    ]
    def __init__(self) -> None: ...
    @classmethod
    def center_of_mass(cls, cfg: CenterOfMassConfig | None = ...) -> "ChessRefiner": ...
    @classmethod
    def forstner(cls, cfg: ForstnerConfig | None = ...) -> "ChessRefiner": ...
    @classmethod
    def saddle_point(cls, cfg: SaddlePointConfig | None = ...) -> "ChessRefiner": ...
    @classmethod
    def ml(cls) -> "ChessRefiner": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ChessRefiner": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "ChessRefiner": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

class RadonRefiner:
    kind: str
    payload: Union[RadonPeakConfig, CenterOfMassConfig]
    def __init__(self) -> None: ...
    @classmethod
    def radon_peak(cls, cfg: RadonPeakConfig | None = ...) -> "RadonRefiner": ...
    @classmethod
    def center_of_mass(cls, cfg: CenterOfMassConfig | None = ...) -> "RadonRefiner": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RadonRefiner": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "RadonRefiner": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# Per-strategy configs
# ---------------------------------------------------------------------------

class ChessConfig:
    ring: ChessRing
    refiner: ChessRefiner
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ChessConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "ChessConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

class RadonConfig:
    ray_radius: int
    image_upsample: int
    response_blur_radius: int
    peak_fit: PeakFitMode
    refiner: RadonRefiner
    def __init__(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RadonConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "RadonConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# Strategy dispatch
# ---------------------------------------------------------------------------

class DetectionStrategy:
    kind: str
    chess: ChessConfig | None
    radon: RadonConfig | None
    def __init__(self) -> None: ...
    @classmethod
    def from_chess(cls, strategy: ChessConfig) -> "DetectionStrategy": ...
    @classmethod
    def from_radon(cls, strategy: RadonConfig) -> "DetectionStrategy": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DetectionStrategy": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "DetectionStrategy": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# Top-level detector config
# ---------------------------------------------------------------------------

class DetectorConfig:
    strategy: DetectionStrategy
    threshold: float
    detection: DetectionParams
    multiscale: MultiscaleConfig
    upscale: UpscaleConfig
    orientation_method: Optional[OrientationMethod]
    merge_radius: float
    def __init__(self) -> None: ...
    @classmethod
    def chess(cls) -> "DetectorConfig": ...
    @classmethod
    def chess_multiscale(cls) -> "DetectorConfig": ...
    @classmethod
    def radon(cls) -> "DetectorConfig": ...
    @classmethod
    def radon_multiscale(cls) -> "DetectorConfig": ...
    def with_threshold(self, value: float) -> "DetectorConfig": ...
    def with_multiscale(self, multiscale: MultiscaleConfig) -> "DetectorConfig": ...
    def with_upscale(self, upscale: UpscaleConfig) -> "DetectorConfig": ...
    def with_orientation_method(self, method: OrientationMethod) -> "DetectorConfig": ...
    def without_orientation(self) -> "DetectorConfig": ...
    def with_merge_radius(self, radius: float) -> "DetectorConfig": ...
    def with_chess(self, **kwargs: Any) -> "DetectorConfig": ...
    def with_radon(self, **kwargs: Any) -> "DetectorConfig": ...
    def with_detection(self, **kwargs: Any) -> "DetectorConfig": ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DetectorConfig": ...
    def to_json(self, *, indent: int | None = ..., sort_keys: bool = ...) -> str: ...
    @classmethod
    def from_json(cls, text: str) -> "DetectorConfig": ...
    @classmethod
    def from_json_file(
        cls, path: Union[str, PathLike[str]]
    ) -> "DetectorConfig": ...
    def pretty(self, *, indent: int = ..., sort_keys: bool = ...) -> str: ...
    def print(self, *, file: TextIO | None = ..., indent: int = ..., sort_keys: bool = ...) -> None: ...

# ---------------------------------------------------------------------------
# Detector
# ---------------------------------------------------------------------------

class Detector:
    def __init__(self, cfg: DetectorConfig | None = ...) -> None: ...
    def detect(self, image: np.ndarray) -> np.ndarray: ...
    def config(self) -> DetectorConfig: ...
    def apply_config(self, cfg: DetectorConfig | None) -> None: ...
    def radon_heatmap(self, image: np.ndarray) -> np.ndarray:
        """Return the intermediate dense Radon-response heatmap.

        Opt-in diagnostic evidence for debugging and visualization —
        the per-pixel Radon response computed internally — not part of
        the normal detection result returned by :meth:`detect`.
        """
        ...

__all__: list[str]
